name: gymmanageros
services:
- name: app
  github:
    branch: laravel-v2
    deploy_on_push: true
    repo: pascalicchio/coachos
  dockerfile_path: Dockerfile
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: "false"
  - key: DB_CONNECTION
    value: pgsql
  - key: DB_HOST
    value: ${db.HOSTNAME}
  - key: DB_PORT
    value: "5432"
  - key: DB_DATABASE
    value: ${db.DATABASE}
  - key: DB_USERNAME
    value: ${db.USERNAME}
  - key: DB_PASSWORD
    value: ${db.PASSWORD}
databases:
- name: db
  engine: PG
  version: "15"
  size: db-s-dev-database
